### ISSUE TITLE
crash when open translation manager

### ISSUE THREAD

**Issue by MohAbbasher** [quran/quran_android#1642]
app crash when opening translation manager with message:

` java.lang.NullPointerException: itemView.findViewById(R.id.translation_title) must not be null
        at com.quran.labs.androidquran.ui.adapter.TranslationsAdapter$TranslationViewHolder.<init>(TranslationsAdapter.kt:145)
        at com.quran.labs.androidquran.ui.adapter.TranslationsAdapter.onCreateViewHolder(TranslationsAdapter.kt:37)
        at com.quran.labs.androidquran.ui.adapter.TranslationsAdapter.onCreateViewHolder(TranslationsAdapter.kt:21)`

**Comment by ahmedre** [comment]
@wiryadev this is probably due to Kotlin migration can you take a look?

**Comment by wiryadev** [comment]
I can confirm it, now it has been fixed, i wil PR this.
![image](https://user-images.githubusercontent.com/26060382/127661985-cfe48046-86df-4bdf-9b5f-6aeca944a2cd.png)
