### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by DoozyDoz** [quran/quran_android#2044]
## Description
With the latest code (master), upon running the app crushes immediately.

#### Stacktrace 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.quran.labs.androidquran.debug, PID: 8219
    java.lang.RuntimeException: Unable to create service com.quran.labs.androidquran.service.QuranDownloadService: java.lang.IllegalArgumentException: replay or extraBufferCapacity must be positive with non-default onBufferOverflow strategy DROP_OLDEST
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: replay or extraBufferCapacity must be positive with non-default onBufferOverflow strategy DROP_OLDEST
        at kotlinx.coroutines.flow.SharedFlowKt.MutableSharedFlow(SharedFlow.kt:271)
        at kotlinx.coroutines.flow.SharedFlowKt.MutableSharedFlow$default(SharedFlow.kt:264)
        at com.quran.mobile.common.download.DownloadInfoStreams.<init>(DownloadInfoStreams.kt:18)
        at com.quran.mobile.common.download.DownloadInfoStreams_Factory.newInstance(DownloadInfoStreams_Factory.kt:23)
        at com.quran.mobile.common.download.DownloadInfoStreams_Factory.get(DownloadInfoStreams_Factory.kt:17)
        at com.quran.mobile.common.download.DownloadInfoStreams_Factory.get(DownloadInfoStreams_Factory.kt:16)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.quran.labs.androidquran.di.component.application.DaggerApplicationComponent$ApplicationComponentImpl.injectQuranDownloadService(DaggerApplicationComponent.java:1140)
        at com.quran.labs.androidquran.di.component.application.DaggerApplicationComponent$ApplicationComponentImpl.inject(DaggerApplicationComponent.java:1016)
        at com.quran.labs.androidquran.service.QuranDownloadService.onCreate(QuranDownloadService.java:154)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3532)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by ahmedre** [comment]
jazakumAllah khairan - I had a fix for this as part of #2027 but I'll open a separate PR for it now to fix it in sha' Allah.
