### ISSUE TITLE
I try to rename package when click setting menu then error like this.

### ISSUE THREAD

**Issue by syaiful9507** [quran/quran_android#948]
05-07 04:12:16.535 886-886/? E/AndroidRuntime: FATAL EXCEPTION: main
                                               Process: com.quran.labs.appscode, PID: 886
                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.quran.labs.appscode/com.quran.labs.appscode.QuranPreferenceActivity}: java.lang.IllegalArgumentException: Platform class android.support.v7.sq annotated [] requires explicit JsonAdapter to be registered
                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2802)
                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:163)
                                                   at android.app.ActivityThread.main(ActivityThread.java:6361)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
                                                Caused by: java.lang.IllegalArgumentException: Platform class android.support.v7.sq annotated [] requires explicit JsonAdapter to be registered
                                                   at com.squareup.moshi.ClassJsonAdapter$1.create(SourceFile:51)
                                                   at com.squareup.moshi.Moshi.adapter(SourceFile:100)
                                                   at com.squareup.moshi.Moshi.adapter(SourceFile:62)
                                                   at android.support.v7.tw.<init>(SourceFile:22)
                                                   at android.support.v7.tx.c(SourceFile:23)
                                                   at android.support.v7.sn.a(SourceFile:15306)
                                                   at android.support.v7.aac.onCreate(SourceFile:35)
                                                   at android.app.Fragment.performCreate(Fragment.java:2336)
                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
                                                   at android.app.BackStackRecord.setLastIn(BackStackRecord.java:860)
                                                   at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:900)
                                                   at android.app.BackStackRecord.run(BackStackRecord.java:728)
                                                   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1580)
                                                   at android.app.FragmentController.execPendingActions(FragmentController.java:371)
                                                   at android.app.Activity.performStart(Activity.java:6890)
                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2704)
                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2802) 
                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549) 
                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                   at android.os.Looper.loop(Looper.java:163) 
                                                   at android.app.ActivityThread.main(ActivityThread.java:6361) 
                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 

> 

- [x] [

1. 

](url)

**Comment by ozbek** [comment]
Where and how did you change the package name?

**Comment by syaiful9507** [comment]
I rename with manually. 
In quran_android/app/src
Like package in main,Madani,naskh,qaloon,shemerly and warsh

**Comment by ozbek** [comment]
Do not rename Java/Kotlin package names. Do that in Gradle build script.
